# mysql-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: "{{ .Values.mysql.image }}:{{ .Values.mysql.tag }}"
        imagePullPolicy: {{ .Values.mysql.pullPolicy }}
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: {{ .Values.mysql.rootPassword | quote }}
          - name: MYSQL_DATABASE
            value: {{ .Values.mysql.database | quote }}
          - name: MYSQL_USER
            value: {{ .Values.mysql.user | quote }}
          - name: MYSQL_PASSWORD
            value: {{ .Values.mysql.password | quote }}
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: {{ .Values.mysql.pvcName }}