apiVersion: v1
kind: Service
metadata:
  name: {{ include "gontabilizador.fullname" . }}
  labels:
    {{- include "gontabilizador.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: nginx
